name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn lint:ext # Lints the Web Extension `manifest.json` file with web-ext.
    - run: yarn build # Not necessary for testing but does run ESLint on the source code
    - run: yarn test
      env:
        CI: true
